export const TYPE_COLORS: { [key: string]: string } = {
    normal: 'bg-gray-400 text-white',
    fire: 'bg-orange-500 text-white',
    water: 'bg-blue-500 text-white',
    electric: 'bg-yellow-400 text-slate-900',
    grass: 'bg-green-500 text-white',
    ice: 'bg-cyan-400 text-slate-900',
    fighting: 'bg-red-700 text-white',
    poison: 'bg-purple-500 text-white',
    ground: 'bg-amber-600 text-white',
    flying: 'bg-indigo-400 text-white',
    psychic: 'bg-pink-500 text-white',
    bug: 'bg-lime-500 text-white',
    rock: 'bg-stone-500 text-white',
    ghost: 'bg-violet-700 text-white',
    dragon: 'bg-indigo-600 text-white',
    steel: 'bg-slate-400 text-white',
    fairy: 'bg-pink-400 text-white',
    dark: 'bg-slate-800 text-white',
    unknown: 'bg-slate-200 text-slate-800'
};

export const TYPE_COLORS_LIGHT: { [key: string]: string } = {
    normal: 'bg-gray-300',
    fire: 'bg-red-200',
    water: 'bg-blue-100',
    electric: 'bg-yellow-100',
    grass: 'bg-green-100',
    ice: 'bg-cyan-100',
    fighting: 'bg-red-100',
    poison: 'bg-purple-300',
    ground: 'bg-amber-200',
    flying: 'bg-indigo-100',
    psychic: 'bg-pink-100',
    bug: 'bg-lime-200',
    rock: 'bg-stone-300',
    ghost: 'bg-violet-100',
    dragon: 'bg-indigo-100',
    steel: 'bg-slate-100',
    fairy: 'bg-pink-100',
    dark: 'bg-slate-100',
    unknown: 'bg-slate-100'
};

export const HOVER_TEXT_COLORS: { [key: string]: string } = {
    normal: 'group-hover:text-gray-500',
    fire: 'group-hover:text-red-600',
    water: 'group-hover:text-blue-600',
    electric: 'group-hover:text-yellow-500',
    grass: 'group-hover:text-green-600',
    ice: 'group-hover:text-cyan-500',
    fighting: 'group-hover:text-red-800',
    poison: 'group-hover:text-purple-600',
    ground: 'group-hover:text-amber-700',
    flying: 'group-hover:text-indigo-500',
    psychic: 'group-hover:text-pink-600',
    bug: 'group-hover:text-lime-600',
    rock: 'group-hover:text-yellow-800',
    ghost: 'group-hover:text-indigo-900',
    dragon: 'group-hover:text-violet-700',
    steel: 'group-hover:text-slate-500',
    dark: 'group-hover:text-gray-800',
    fairy: 'group-hover:text-pink-400',
    unknown: 'group-hover:text-gray-400',
    shadow: 'group-hover:text-slate-900'
};